user default off nopass nocommands nokeys
user openig-app1 on >REDIS_PASSWORD_APP1_PLACEHOLDER ~app1:* +@all
user openig-app2 on >REDIS_PASSWORD_APP2_PLACEHOLDER ~app2:* +@all
user openig-app3 on >REDIS_PASSWORD_APP3_PLACEHOLDER ~app3:* +@all
user openig-app4 on >REDIS_PASSWORD_APP4_PLACEHOLDER ~app4:* +@all
user openig-app5 on >REDIS_PASSWORD_APP5_PLACEHOLDER ~app5:* +@all
user openig-app6 on >REDIS_PASSWORD_APP6_PLACEHOLDER ~app6:* +@all
