networks:
  frontend-c:
    driver: bridge
  backend-c:
    driver: bridge

services:
  nginx-c:
    image: nginx:1.25-alpine
    ports:
      - "18080:80"
    networks:
      - frontend-c
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - openig-c1
      - openig-c2

  openig-c1:
    image: openidentityplatform/openig
    networks:
      - frontend-c
      - backend-c
    volumes:
      - ./openig_home:/opt/openig
    environment:
      OPENIG_BASE: "/opt/openig"
      OPENIG_PUBLIC_URL: "http://openig-c.sso.local:10080"
      KEYCLOAK_BROWSER_URL: "http://auth.sso.local:8080"
      REDIS_HOST: "redis-c"
      VAULT_ADDR: "http://vault-c:8200"
      VAULT_ROLE_ID_FILE: "/opt/openig/vault/role_id"
      VAULT_SECRET_ID_FILE: "/opt/openig/vault/secret_id"

  openig-c2:
    image: openidentityplatform/openig
    networks:
      - frontend-c
      - backend-c
    volumes:
      - ./openig_home:/opt/openig
    environment:
      OPENIG_BASE: "/opt/openig"
      OPENIG_PUBLIC_URL: "http://openig-c.sso.local:10080"
      KEYCLOAK_BROWSER_URL: "http://auth.sso.local:8080"
      REDIS_HOST: "redis-c"
      VAULT_ADDR: "http://vault-c:8200"
      VAULT_ROLE_ID_FILE: "/opt/openig/vault/role_id"
      VAULT_SECRET_ID_FILE: "/opt/openig/vault/secret_id"

  grafana:
    image: grafana/grafana:latest
    networks:
      - backend-c
    environment:
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_SERVER_ROOT_URL: "http://grafana-c.sso.local:18080"

  mariadb:
    image: mariadb:11
    networks:
      - backend-c
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "appdb"
      MYSQL_USER: "alice"
      MYSQL_PASSWORD: "AlicePass123"

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - backend-c
    environment:
      PMA_HOST: "mariadb"
      PMA_AUTH_TYPE: "http"
    volumes:
      - ./openig_home/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro

  redis-c:
    image: redis:7-alpine
    networks:
      - backend-c

  vault-c:
    image: hashicorp/vault:1.15
    networks:
      - backend-c
    cap_add:
      - IPC_LOCK
    command: server
    volumes:
      - ./vault/config:/vault/config:ro
      - ./vault/data:/vault/data
      - ./vault/file:/vault/file
      - ./vault/init:/vault/init
